services:
  - type: web
    name: sign-language-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: python app.py
    rootDir: backend
    autoDeploy: true
